FROM mcr.microsoft.com/dotnet/runtime:10.0-windowsservercore-ltsc2025

WORKDIR /DSC

COPY ./Utilities/Install-M365DSCAndDependencies.ps1 /DSC/Install-M365DSCAndDependencies.ps1

SHELL ["cmd", "/S", "/C"]

RUN powershell -Command .\Install-M365DSCAndDependencies.ps1

# This next command should be removed after next release of Microsoft365DSC
COPY ["./Modules/Microsoft365DSC/Modules/*.psm1", "/Program Files/WindowsPowerShell/Modules/Microsoft365DSC/1.26.701.1/Modules/"]

ENTRYPOINT ["pwsh", "-NoLogo"]
